In [1]:
pip install pandas


[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import pandas as pd
df = pd.read_csv("LanguageDetection.csv")
print(df.shape)

(10337, 2)


In [4]:
import pandas as pd

# Read the data from Language Detection.csv
file_path = 'LanguageDetection.csv'
df = pd.read_csv(file_path)

# Remove null values
df_cleaned = df.dropna()

# Save the cleaned data to a new CSV file
output_path = 'cleaned_data.csv'
df_cleaned.to_csv(output_path, index=False)

print(f"Cleaned data saved to {output_path}")


Cleaned data saved to cleaned_data.csv


In [5]:
df1 = pd.read_csv("cleaned_data.csv")
print(df1.shape)

(10337, 2)


In [6]:
pip install nltk

     ---------------------------------------- 1.5/1.5 MB 195.2 kB/s eta 0:00:00
     -------------------------------------- 78.3/78.3 kB 155.6 kB/s eta 0:00:00
     ------------------------------------ 269.6/269.6 kB 448.6 kB/s eta 0:00:00
     ------------------------------------ 302.2/302.2 kB 236.4 kB/s eta 0:00:00
     -------------------------------------- 97.9/97.9 kB 122.1 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [18]:
import pandas as pd
import re
from nltk.tokenize import word_tokenize

# Read the data from LanguageDataset.csv
file_path = 'LanguageDetection.csv'
df = pd.read_csv(file_path)

# Ensure the column names are as expected ('Text' and 'Language')
df.columns = df.columns.str.strip()  # Remove leading/trailing whitespaces

# Make sure to replace 'Text' with the actual column name in your dataset
text_column_name = 'Text'

# Function for text cleaning and preprocessing
def preprocess_text(text):
    # Remove special characters, numbers, and other non-text elements
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Convert text to lowercase
    text = text.lower()

    return text

# Apply text preprocessing to the specified column
df['Text'] = df[text_column_name].apply(preprocess_text).apply(word_tokenize)

# Create a new DataFrame with only the 'tokens' and 'Language' columns
df_output = df[['Text', 'Language']]
# df_output.rename('Text')
# Save the preprocessed data to a new CSV file
output_path = 'preprocessed.csv'
df_output.to_csv(output_path, index=False)

print(f"Preprocessed data saved to {output_path}")


Preprocessed data saved to preprocessed.csv


In [19]:
pip install scikit-learn

     ---------------------------------------- 9.3/9.3 MB 446.6 kB/s eta 0:00:00
     -------------------------------------- 44.1/44.1 MB 457.6 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split

# Read the preprocessed data from 'preprocessed.csv'
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# Split the data into training and testing sets
train_data, test_data, train_labels, test_labels = train_test_split(
    df['Text'], df['Language'], test_size=0.2, random_state=42
)

# Bag-of-Words (BoW) representation
bow_vectorizer = CountVectorizer()
train_bow = bow_vectorizer.fit_transform(train_data)
test_bow = bow_vectorizer.transform(test_data)

# TF-IDF representation
tfidf_vectorizer = TfidfVectorizer()
train_tfidf = tfidf_vectorizer.fit_transform(train_data)
test_tfidf = tfidf_vectorizer.transform(test_data)

# Display the feature matrices
print("Bag-of-Words (BoW) representation:")
print(train_bow.toarray())

print("\nTF-IDF representation:")
print(train_tfidf.toarray())

Bag-of-Words (BoW) representation:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

TF-IDF representation:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Read the preprocessed data from 'preprocessed.csv'
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# Split the data into training and testing sets
train_data, test_data, train_labels, test_labels = train_test_split(
    df['Text'], df['Language'], test_size=0.2, random_state=42
)

# TF-IDF representation
tfidf_vectorizer = TfidfVectorizer()
train_tfidf = tfidf_vectorizer.fit_transform(train_data)
test_tfidf = tfidf_vectorizer.transform(test_data)

# Initialize and train the Support Vector Machine (SVM) model
svm_model = SVC(kernel='linear')  # You can experiment with different kernels (linear, rbf, etc.)
svm_model.fit(train_tfidf, train_labels)

# Predictions on the test set
predictions = svm_model.predict(test_tfidf)

# Evaluate the model
accuracy = accuracy_score(test_labels, predictions)
classification_report_result = classification_report(test_labels, predictions)

# Display evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:")
print(classification_report_result)

Accuracy: 0.72

Classification Report:
              precision    recall  f1-score   support

      Arabic       1.00      0.02      0.04       106
      Danish       0.94      0.88      0.91        73
       Dutch       1.00      0.93      0.96       111
     English       0.97      0.97      0.97       291
      French       0.99      0.93      0.96       219
      German       0.99      0.92      0.96        93
       Greek       0.25      0.01      0.03        68
       Hindi       0.00      0.00      0.00        10
     Italian       1.00      0.92      0.96       145
     Kannada       0.00      0.00      0.00        66
   Malayalam       0.00      0.00      0.00       121
  Portugeese       0.99      0.92      0.96       144
     Russian       0.20      0.99      0.33       136
     Spanish       0.97      0.93      0.95       160
    Sweedish       0.98      0.88      0.93       133
       Tamil       0.00      0.00      0.00        87
     Turkish       1.00      0.80      0.8

c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

In [23]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

# Read the preprocessed data from 'preprocessed.csv'
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# Split the data into training and testing sets
train_data, test_data, train_labels, test_labels = train_test_split(
    df['Text'], df['Language'], test_size=0.2, random_state=42
)

# TF-IDF representation
tfidf_vectorizer = TfidfVectorizer()
train_tfidf = tfidf_vectorizer.fit_transform(train_data)
test_tfidf = tfidf_vectorizer.transform(test_data)

# Initialize and train the Support Vector Machine (SVM) model
svm_model = SVC(kernel='linear')  # You can experiment with different kernels (linear, rbf, etc.)
svm_model.fit(train_tfidf, train_labels)

# Predictions on the test set
predictions = svm_model.predict(test_tfidf)

# Evaluate the model
accuracy = accuracy_score(test_labels, predictions)
classification_report_result = classification_report(test_labels, predictions)

# Display evaluation metrics
print(f"Accuracy before hyperparameter tuning: {accuracy:.2f}")
print("\nClassification Report before hyperparameter tuning:")
print(classification_report_result)

# Hyperparameter tuning using GridSearchCV
param_grid = {'C': [0.1, 1, 10, 100], 'gamma': ['scale', 'auto'], 'kernel': ['linear', 'rbf']}
grid_search = GridSearchCV(SVC(), param_grid, cv=5)
grid_search.fit(train_tfidf, train_labels)

# Best hyperparameters from the grid search
best_params = grid_search.best_params_

# Re-train the model with the best hyperparameters
best_svm_model = SVC(**best_params)
best_svm_model.fit(train_tfidf, train_labels)

# Predictions on the test set using the tuned model
tuned_predictions = best_svm_model.predict(test_tfidf)

# Evaluate the tuned model
tuned_accuracy = accuracy_score(test_labels, tuned_predictions)
tuned_classification_report_result = classification_report(test_labels, tuned_predictions)

# Display evaluation metrics after hyperparameter tuning
print(f"\nBest Hyperparameters: {best_params}")
print(f"Accuracy after hyperparameter tuning: {tuned_accuracy:.2f}")
print("\nClassification Report after hyperparameter tuning:")
print(tuned_classification_report_result)


c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

Accuracy before hyperparameter tuning: 0.72

Classification Report before hyperparameter tuning:
              precision    recall  f1-score   support

      Arabic       1.00      0.02      0.04       106
      Danish       0.94      0.88      0.91        73
       Dutch       1.00      0.93      0.96       111
     English       0.97      0.97      0.97       291
      French       0.99      0.93      0.96       219
      German       0.99      0.92      0.96        93
       Greek       0.25      0.01      0.03        68
       Hindi       0.00      0.00      0.00        10
     Italian       1.00      0.92      0.96       145
     Kannada       0.00      0.00      0.00        66
   Malayalam       0.00      0.00      0.00       121
  Portugeese       0.99      0.92      0.96       144
     Russian       0.20      0.99      0.33       136
     Spanish       0.97      0.93      0.95       160
    Sweedish       0.98      0.88      0.93       133
       Tamil       0.00      0.00     

c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

In [24]:
# Display evaluation metrics before hyperparameter tuning
print(f"Accuracy before hyperparameter tuning: {accuracy:.2f}")
print("\nClassification Report before hyperparameter tuning:")
print(classification_report_result)

# Display evaluation metrics after hyperparameter tuning
print(f"\nBest Hyperparameters: {best_params}")
print(f"Accuracy after hyperparameter tuning: {tuned_accuracy:.2f}")
print("\nClassification Report after hyperparameter tuning:")
print(tuned_classification_report_result)


Accuracy before hyperparameter tuning: 0.72

Classification Report before hyperparameter tuning:
              precision    recall  f1-score   support

      Arabic       1.00      0.02      0.04       106
      Danish       0.94      0.88      0.91        73
       Dutch       1.00      0.93      0.96       111
     English       0.97      0.97      0.97       291
      French       0.99      0.93      0.96       219
      German       0.99      0.92      0.96        93
       Greek       0.25      0.01      0.03        68
       Hindi       0.00      0.00      0.00        10
     Italian       1.00      0.92      0.96       145
     Kannada       0.00      0.00      0.00        66
   Malayalam       0.00      0.00      0.00       121
  Portugeese       0.99      0.92      0.96       144
     Russian       0.20      0.99      0.33       136
     Spanish       0.97      0.93      0.95       160
    Sweedish       0.98      0.88      0.93       133
       Tamil       0.00      0.00     

In [25]:
pip install flask

     -------------------------------------- 99.7/99.7 kB 143.2 kB/s eta 0:00:00
     ------------------------------------- 226.7/226.7 kB 91.1 kB/s eta 0:00:00
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
from flask import Flask, request, jsonify
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
import joblib

app = Flask(__name__)

# Load the preprocessed data
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# TF-IDF representation
tfidf_vectorizer = TfidfVectorizer()
X = tfidf_vectorizer.fit_transform(df['Text'])

# Train the SVM model
svm_model = SVC(kernel='linear')
svm_model.fit(X, df['Language'])

# Save the trained model and vectorizer
model_path = 'language_detection_model.joblib'
vectorizer_path = 'tfidf_vectorizer.joblib'
joblib.dump(svm_model, model_path)
joblib.dump(tfidf_vectorizer, vectorizer_path)

@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Get the input text from the request
        data = request.get_json()
        text = data['text']

        # Preprocess and vectorize the input text
        text = text.lower()
        text_tfidf = tfidf_vectorizer.transform([text])

        # Predict the language
        prediction = svm_model.predict(text_tfidf)[0]

        # Return the prediction
        return jsonify({'language': prediction})

    except Exception as e:
        return jsonify({'error': str(e)})

if __name__ == '__main__':
    app.run(debug=True)


 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat


SystemExit: 1

C:\Users\KIRANMAI\AppData\Roaming\Python\Python310\site-packages\IPython\core\interactiveshell.py:3558: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
import joblib
import time
from sklearn.model_selection import train_test_split
from sklearn import metrics

# Function to monitor model performance
def monitor_model_performance(model, vectorizer, data):
    # Preprocess and vectorize the data
    text_tfidf = vectorizer.transform(data['Text'])

    # Predict the language
    predictions = model.predict(text_tfidf)

    # Evaluate the model
    accuracy = metrics.accuracy_score(data['Language'], predictions)
    return accuracy

# Load the preprocessed data (or replace with your data loading logic)
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# Split data into training and testing sets
train_data, test_data = train_test_split(df, test_size=0.2, random_state=42)

# Train the model (or replace with your training logic)
tfidf_vectorizer = TfidfVectorizer()
X_train = tfidf_vectorizer.fit_transform(train_data['Text'])
svm_model = SVC()
svm_model.fit(X_train, train_data['Language'])

# Monitor model performance over time
while True:
    # Simulate new data coming in (for testing purposes)
    # In a production environment, replace this with actual data fetching logic.
    new_data = test_data.sample(frac=0.2, random_state=42)

    # Monitor model performance on the new data
    accuracy = monitor_model_performance(svm_model, tfidf_vectorizer, new_data)
    print(f"Model Accuracy: {accuracy:.2f}")

    # # Schedule the monitoring every 24 hours
    # time.sleep()  # Sleep for 24 hours


Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74
Model Accuracy: 0.74


KeyboardInterrupt: 

In [32]:
pip install joblib

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Read the preprocessed data from 'preprocessed.csv'
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# Split the data into training and testing sets
train_data, test_data, train_labels, test_labels = train_test_split(
    df['Text'], df['Language'], test_size=0.2, random_state=42
)

# TF-IDF representation
tfidf_vectorizer = TfidfVectorizer()
train_tfidf = tfidf_vectorizer.fit_transform(train_data)
test_tfidf = tfidf_vectorizer.transform(test_data)

# Initialize and train the Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)  # You can adjust n_estimators as needed
rf_model.fit(train_tfidf, train_labels)

# Predictions on the test set
predictions = rf_model.predict(test_tfidf)

# Evaluate the model
accuracy = accuracy_score(test_labels, predictions)
classification_report_result = classification_report(test_labels, predictions)

# Display evaluation metrics
print(f"Accuracy: {accuracy:.2f}")
print("\nClassification Report:")
print(classification_report_result)

Accuracy: 0.73

Classification Report:
              precision    recall  f1-score   support

      Arabic       0.67      0.02      0.04       106
      Danish       0.94      0.85      0.89        73
       Dutch       0.99      0.94      0.96       111
     English       0.96      0.98      0.97       291
      French       0.98      0.94      0.96       219
      German       1.00      0.95      0.97        93
       Greek       0.33      0.04      0.08        68
       Hindi       0.00      0.00      0.00        10
     Italian       0.98      0.90      0.94       145
     Kannada       0.33      0.02      0.03        66
   Malayalam       0.00      0.00      0.00       121
  Portugeese       0.95      0.94      0.94       144
     Russian       0.22      0.99      0.35       136
     Spanish       0.90      0.94      0.92       160
    Sweedish       0.95      0.93      0.94       133
       Tamil       0.00      0.00      0.00        87
     Turkish       0.99      0.87      0.9

c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Read the preprocessed data from 'preprocessed.csv'
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# Split the data into training and testing sets
train_data, test_data, train_labels, test_labels = train_test_split(
    df['Text'], df['Language'], test_size=0.2, random_state=42
)

# TF-IDF representation
tfidf_vectorizer = TfidfVectorizer()
train_tfidf = tfidf_vectorizer.fit_transform(train_data)
test_tfidf = tfidf_vectorizer.transform(test_data)

# Initialize and train the Support Vector Machine (SVM) model
svm_model = SVC(kernel='linear', decision_function_shape='ovr')  # 'ovr' for multiclass
svm_model.fit(train_tfidf, train_labels)

# Save the trained model and vectorizer
model_path = 'multilingual_detection_model.joblib'
vectorizer_path = 'tfidf_vectorizer_multilingual.joblib'
joblib.dump(svm_model, model_path)
joblib.dump(tfidf_vectorizer, vectorizer_path)

# Predictions on the test set
predictions = svm_model.predict(test_tfidf)

# Evaluate the model
accuracy = accuracy_score(test_labels, predictions)
classification_report_result = classification_report(test_labels, predictions)

# Display evaluation metrics
print(f"Accuracy before hyperparameter tuning: {accuracy:.2f}")
print("\nClassification Report before hyperparameter tuning:")
print(classification_report_result)


Accuracy before hyperparameter tuning: 0.72

Classification Report before hyperparameter tuning:
              precision    recall  f1-score   support

      Arabic       1.00      0.02      0.04       106
      Danish       0.94      0.88      0.91        73
       Dutch       1.00      0.93      0.96       111
     English       0.97      0.97      0.97       291
      French       0.99      0.93      0.96       219
      German       0.99      0.92      0.96        93
       Greek       0.25      0.01      0.03        68
       Hindi       0.00      0.00      0.00        10
     Italian       1.00      0.92      0.96       145
     Kannada       0.00      0.00      0.00        66
   Malayalam       0.00      0.00      0.00       121
  Portugeese       0.99      0.92      0.96       144
     Russian       0.20      0.99      0.33       136
     Spanish       0.97      0.93      0.95       160
    Sweedish       0.98      0.88      0.93       133
       Tamil       0.00      0.00     

c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\KIRANMAI\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

In [3]:
pip install langdetect

     -------------------------------------- 981.5/981.5 kB 1.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for langdetect, since package 'wheel' is not installed.
  Running setup.py install for langdetect: started
  Running setup.py install for langdetect: finished with status 'done'
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
from langdetect import detect

In [5]:
detect("this is kiranmai")

'en'

In [6]:
from langdetect import detect_langs

In [9]:
detect_langs("ఎలా ఉన్నావ్")

[te:0.9999999370715171]

In [3]:
import numpy as np
import pandas as pd
import re

In [4]:
df=pd.read_csv('LanguageDetection.csv')

In [5]:
df.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10337 entries, 0 to 10336
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Text      10337 non-null  object
 1   Language  10337 non-null  object
dtypes: object(2)
memory usage: 161.6+ KB


In [7]:
X=df['Text']
y=df['Language']

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [10]:
df_list=[]
for text in X:
    text=re.sub(r'[!@#$(),n"%^*?:;~`0-9]','',text)
    text=re.sub(r'[[]]','',text)
    text=text.lower()
    df_list.append(text)


In [11]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(df_list).toarray()
print(X.shape)
len(df_list)


(10337, 38665)


10337

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.2,random_state=41) 

In [16]:
from sklearn.linear_model import LogisticRegression
ada = LogisticRegression()
y_pred=ada.fit(X_train,y_train).predict(X_test)

In [17]:
from sklearn.metrics import f1_score ,confusion_matrix
ac=f1_score(y_test,y_pred,average='macro')


In [18]:
print(f'Accuracy={ac:.2f}')

Accuracy=0.95


In [19]:
def prediction(text):
    x=cv.transform([text]).toarray()
    lang=ada.predict(x)
    lang=le.inverse_transform(lang)
    print('The language is in',lang[0])
    

In [20]:
prediction('Hello my name is marshall')

The language is in English


In [21]:
prediction('Comment allez-vous ?')

The language is in French


In [22]:
prediction('आप से मिलकर बहुत ख़ुशी हुई')

The language is in Hindi


In [25]:
pip install langid



[notice] A new release of pip available: 22.2.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 1.9/1.9 MB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Using legacy 'setup.py install' for langid, since package 'wheel' is not installed.
  Running setup.py install for langid: started
  Running setup.py install for langid: finished with status 'done'


In [26]:
import pandas as pd
import langid

# Load the preprocessed data (or replace with your data loading logic)
preprocessed_path = 'preprocessed.csv'
df = pd.read_csv(preprocessed_path)

# Assume 'Text' is the column containing the text data
texts = df['Text'].tolist()

# Detect languages using langid
langid_results = [langid.classify(text) for text in texts]

# Extract detected languages
detected_languages = [lang for lang, _ in langid_results]

# Add detected languages to the dataframe
df['DetectedLanguage'] = detected_languages

# Display the dataframe with detected languages
print(df[['Text', 'DetectedLanguage']])


                                                    Text DetectedLanguage
0      ['nature', 'in', 'the', 'broadest', 'sense', '...               es
1      ['nature', 'can', 'refer', 'to', 'the', 'pheno...               en
2      ['the', 'study', 'of', 'nature', 'is', 'a', 'l...               en
3      ['although', 'humans', 'are', 'part', 'of', 'n...               en
4      ['the', 'word', 'nature', 'is', 'borrowed', 'f...               en
...                                                  ...              ...
10332                                                 []               en
10333                                                 []               en
10334                                                 []               en
10335                                            ['ess']               en
10336                                                 []               en

[10337 rows x 2 columns]
